plugins {
    id 'java'
}

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net/releases/' }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'net.neoforged:accesstransformers:10.0.1'
    testImplementation 'ch.qos.logback:logback-classic:1.5.6'
}

test {
    useJUnitPlatform()
    systemProperty 'file.encoding', 'UTF-8'
    testLogging {
        events 'failed', 'skipped'
        exceptionFormat 'full'
    }
}
