plugins {
    id 'java'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

dependencies {
    implementation 'net.bytebuddy:byte-buddy:1.17.7'
}

tasks.named('jar', Jar).configure {
    archiveBaseName = 'bootoptim-all-packets-agent'
    archiveVersion = ''
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
                'Premain-Class': 'dev.wachipayox.bootoptim.allpackets.AllPacketsAgent',
                'Can-Redefine-Classes': 'false',
                'Can-Retransform-Classes': 'false'
        )
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
