plugins {
    id 'java'
}

version = rootProject.version
group = rootProject.group

base {
    archivesName = 'bootoptim-modlauncher-tail-agent'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.ow2.asm:asm:9.7.1'
    implementation 'org.ow2.asm:asm-tree:9.7.1'

    testImplementation platform('org.junit:junit-bom:5.11.4')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar', Jar).configure {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
                'Premain-Class': 'dev.wachipayox.bootoptim.tailagent.ModLauncherTailAgent',
                'Can-Redefine-Classes': 'false',
                'Can-Retransform-Classes': 'false',
                'Implementation-Version': project.version)
    }
    from {
        configurations.runtimeClasspath.collect { dependency ->
            dependency.isDirectory() ? dependency : zipTree(dependency)
        }
    }
}

tasks.named('test', Test).configure {
    useJUnitPlatform()
}
